name: nightly
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/plan-and-build.yml
    with:
      force: false
      push: true
    secrets: inherit
