name: on-push
on:
  push:
    branches: [main]
    paths: ['catalog/**', 'builders/**']
  pull_request:
    paths: ['catalog/**', 'builders/**']

jobs:
  pipeline:
    permissions:
      contents: write
      packages: write
      pull-requests: write
      id-token: write
    uses: ./.github/workflows/plan-and-build.yml
    with:
      force: false
      push: true
    secrets: inherit
