name: security-rebuild
on:
  repository_dispatch:
    types: [security-rebuild]

jobs:
  pipeline:
    uses: ./.github/workflows/plan-and-build.yml
    with:
      force: true
      push: true
    secrets: inherit
