name: security-rebuild
on:
  repository_dispatch:
    types: [security-rebuild]

jobs:
  pipeline:
    permissions:
      contents: write
      packages: write
      pull-requests: write
      id-token: write
    uses: ./.github/workflows/plan-and-build.yml
    with:
      force: true
      push: true
    secrets: inherit
